# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_auto_layout_post(self) -> None:
        """Test case for auto_layout_post

        """
        pass

    def test_auto_orient_post(self) -> None:
        """Test case for auto_orient_post

        """
        pass

    def test_auto_support_post(self) -> None:
        """Test case for auto_support_post

        """
        pass

    def test_export_post(self) -> None:
        """Test case for export_post

        """
        pass

    def test_load_form_post(self) -> None:
        """Test case for load_form_post

        """
        pass

    def test_models_id_delete(self) -> None:
        """Test case for models_id_delete

        """
        pass

    def test_save_form_post(self) -> None:
        """Test case for save_form_post

        """
        pass

    def test_scene_get(self) -> None:
        """Test case for scene_get

        """
        pass

    def test_scene_import_model_post(self) -> None:
        """Test case for scene_import_model_post

        """
        pass

    def test_scene_post(self) -> None:
        """Test case for scene_post

        """
        pass

    def test_v1_print_post(self) -> None:
        """Test case for v1_print_post

        """
        pass

    def test_v1_slice_post(self) -> None:
        """Test case for v1_slice_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
