# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs.models.scene_import_model_post_request import SceneImportModelPostRequest

class TestSceneImportModelPostRequest(unittest.TestCase):
    """SceneImportModelPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SceneImportModelPostRequest:
        """Test SceneImportModelPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SceneImportModelPostRequest`
        """
        model = SceneImportModelPostRequest()
        if include_optional:
            return SceneImportModelPostRequest(
                file = '',
                repair_behavior = 'IGNORE',
                name = '',
                position = formlabs.models.scene_position_model.ScenePositionModel(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                orientation = formlabs.models.orientation_model.OrientationModel(),
                scale = 1.337,
                units = 'DETECTED'
            )
        else:
            return SceneImportModelPostRequest(
                file = '',
        )
        """

    def testSceneImportModelPostRequest(self):
        """Test SceneImportModelPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
