# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs.models.direction_vectors_model import DirectionVectorsModel

class TestDirectionVectorsModel(unittest.TestCase):
    """DirectionVectorsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DirectionVectorsModel:
        """Test DirectionVectorsModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DirectionVectorsModel`
        """
        model = DirectionVectorsModel()
        if include_optional:
            return DirectionVectorsModel(
                z_direction = [
                    1.337
                    ],
                x_direction = [
                    1.337
                    ]
            )
        else:
            return DirectionVectorsModel(
                z_direction = [
                    1.337
                    ],
        )
        """

    def testDirectionVectorsModel(self):
        """Test DirectionVectorsModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
