# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs.models.transform_matrix_model import TransformMatrixModel

class TestTransformMatrixModel(unittest.TestCase):
    """TransformMatrixModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransformMatrixModel:
        """Test TransformMatrixModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransformMatrixModel`
        """
        model = TransformMatrixModel()
        if include_optional:
            return TransformMatrixModel(
                linear = [
                    [
                        1.337
                        ]
                    ]
            )
        else:
            return TransformMatrixModel(
                linear = [
                    [
                        1.337
                        ]
                    ],
        )
        """

    def testTransformMatrixModel(self):
        """Test TransformMatrixModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
