# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs.models.model_properties import ModelProperties

class TestModelProperties(unittest.TestCase):
    """ModelProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelProperties:
        """Test ModelProperties
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelProperties`
        """
        model = ModelProperties()
        if include_optional:
            return ModelProperties(
                id = '',
                name = '',
                position = formlabs.models.scene_position_model.ScenePositionModel(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                orientation = formlabs.models.euler_angles_model.EulerAnglesModel(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                scale = 1.337,
                units = 'MILLIMETERS',
                bbox = formlabs.models.model_properties_bbox.ModelProperties_bbox(
                    min_corner = formlabs.models.scene_position_model.ScenePositionModel(
                        x = 1.337, 
                        y = 1.337, 
                        z = 1.337, ), 
                    max_corner = formlabs.models.scene_position_model.ScenePositionModel(
                        x = 1.337, 
                        y = 1.337, 
                        z = 1.337, ), ),
                original_file = '',
                visible = True,
                has_supports = True,
                in_bounds = True
            )
        else:
            return ModelProperties(
        )
        """

    def testModelProperties(self):
        """Test ModelProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
