# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.modifying_a_scene_api import ModifyingASceneApi


class TestModifyingASceneApi(unittest.TestCase):
    """ModifyingASceneApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModifyingASceneApi()

    def tearDown(self) -> None:
        pass

    def test_scene_import_model_post(self) -> None:
        """Test case for scene_import_model_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
