# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs.models.units_model import UnitsModel

class TestUnitsModel(unittest.TestCase):
    """UnitsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitsModel(self):
        """Test UnitsModel"""
        # inst = UnitsModel()

if __name__ == '__main__':
    unittest.main()
